### ISSUE TITLE
Jupyter Slurm environment or extension not configured

### ISSUE THREAD

**Issue by ndjones** [nesi/nesi-ood-jupyterlab-app#6]
There is a Slurm environment available on logging into jupyter. launching it shows nothing as there is no slurm cluster. it does throw errors.

In my `session.log` i get the following error repeatedly

```
[I 2024-08-20 07:15:15.144 ServerApp] SlurmCommandHandler.initialize(): sbatch <Logger ServerApp (DEBUG)>
[I 2024-08-20 07:15:15.144 ServerApp] SbatchHandler.post() - sbatch request: HTTPServerRequest(protocol='http', host='10.16.0.136:32021', method='POST', uri='/node/10.16.0.136/32021/jupyterlab_slurm/sbatch?inputType=contents&outputDir=%2Fnesi%2Fhome%2Fnjon001%2F&1724138114984', version='HTTP/1.1', remote_ip='10.16.0.136') b'{"input":"echo \\"hello world\\""}', inputType: contents, outputDir: /nesi/home/njon001/
[I 2024-08-20 07:15:15.144 ServerApp] Writing script data to temp file for sbatch: echo "hello world"
[I 2024-08-20 07:15:15.144 ServerApp] sbatch call - sbatch b'echo "hello world"' /nesi/home/njon001/
[I 2024-08-20 07:15:15.145 ServerApp] SlurmCommandHandler._run_command(): sbatch 10 /nesi/home/njon001/
[I 2024-08-20 07:15:15.145 ServerApp] SlurmCommandHandler._run_command(): ['sbatch']
[E 2024-08-20 07:15:15.150 ServerApp] Error running sbatch: Attempted to run: command - sbatch, script - echo "hello world", dir - /nesi/home/njon001/. Check console for more details.
[E 2024-08-20 07:15:15.150 ServerApp] [Errno 2] No such file or directory: 'sbatch'
    Traceback (most recent call last):
      File "/opt/nesi/CS400_centos7_bdw/JupyterLab/2023.11.0-gimkl-2022a-3.6.3/lib/python3.11/site-packages/jupyterlab_slurm/handlers.py", line 307, in run_command
        out = await self._run_command(self._slurm_command, stdin=temp.fileno(), cwd=outputDir)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/nesi/CS400_centos7_bdw/JupyterLab/2023.11.0-gimkl-2022a-3.6.3/lib/python3.11/site-packages/jupyterlab_slurm/handlers.py", line 109, in _run_command
        process = await asyncio.create_subprocess_exec(*commands,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/nesi/CS400_centos7_bdw/Python/3.11.3-gimkl-2022a/lib/python3.11/asyncio/subprocess.py", line 218, in create_subprocess_exec
        transport, protocol = await loop.subprocess_exec(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/nesi/CS400_centos7_bdw/Python/3.11.3-gimkl-2022a/lib/python3.11/asyncio/base_events.py", line 1694, in subprocess_exec
        transport = await self._make_subprocess_transport(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/nesi/CS400_centos7_bdw/Python/3.11.3-gimkl-2022a/lib/python3.11/asyncio/unix_events.py", line 207, in _make_subprocess_transport
        transp = _UnixSubprocessTransport(self, protocol, args, shell,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/nesi/CS400_centos7_bdw/Python/3.11.3-gimkl-2022a/lib/python3.11/asyncio/base_subprocess.py", line 36, in __init__
        self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
      File "/opt/nesi/CS400_centos7_bdw/Python/3.11.3-gimkl-2022a/lib/python3.11/asyncio/unix_events.py", line 810, in _start
        self._proc = subprocess.Popen(
                     ^^^^^^^^^^^^^^^^^
      File "/opt/nesi/CS400_centos7_bdw/Python/3.11.3-gimkl-2022a/lib/python3.11/subprocess.py", line 1024, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/opt/nesi/CS400_centos7_bdw/Python/3.11.3-gimkl-2022a/lib/python3.11/subprocess.py", line 1917, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'sbatch'
[I 2024-08-20 07:15:15.151 ServerApp] out: {'responseMessage': 'Failure: sbatch ', 'returncode': 1, 'errorMessage': 'Attempted to run: command - sbatch, script - echo "hello world", dir - /nesi/home/njon001/. Check console for more details.'}
```

**Comment by chrisdjscott** [comment]
it doesn't kill the session but I also get the same error in the log

```
[E 2024-08-20 20:39:11.177 ServerApp] [Errno 2] No such file or directory: 'squeue'
    Traceback (most recent call last):
      File "/opt/nesi/CS400_centos7_bdw/JupyterLab/2023.11.0-gimkl-2022a-3.6.3/lib/python3.11/site-packages/jupyterlab_slurm/handlers.py", line 435, in run_command
        out = await self._run_command(exec_command)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/nesi/CS400_centos7_bdw/JupyterLab/2023.11.0-gimkl-2022a-3.6.3/lib/python3.11/site-packages/jupyterlab_slurm/handlers.py", line 109, in _run_command
        process = await asyncio.create_subprocess_exec(*commands,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/nesi/CS400_centos7_bdw/Python/3.11.3-gimkl-2022a/lib/python3.11/asyncio/subprocess.py", line 218, in create_subprocess_exec
        transport, protocol = await loop.subprocess_exec(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/nesi/CS400_centos7_bdw/Python/3.11.3-gimkl-2022a/lib/python3.11/asyncio/base_events.py", line 1694, in subprocess_exec
        transport = await self._make_subprocess_transport(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/nesi/CS400_centos7_bdw/Python/3.11.3-gimkl-2022a/lib/python3.11/asyncio/unix_events.py", line 207, in _make_subprocess_transport
        transp = _UnixSubprocessTransport(self, protocol, args, shell,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/nesi/CS400_centos7_bdw/Python/3.11.3-gimkl-2022a/lib/python3.11/asyncio/base_subprocess.py", line 36, in __init__
        self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
      File "/opt/nesi/CS400_centos7_bdw/Python/3.11.3-gimkl-2022a/lib/python3.11/asyncio/unix_events.py", line 810, in _start
        self._proc = subprocess.Popen(
                     ^^^^^^^^^^^^^^^^^
      File "/opt/nesi/CS400_centos7_bdw/Python/3.11.3-gimkl-2022a/lib/python3.11/subprocess.py", line 1024, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/opt/nesi/CS400_centos7_bdw/Python/3.11.3-gimkl-2022a/lib/python3.11/subprocess.py", line 1917, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'squeue'
```

once we update the module this should go away as you removed the slurm extension

**Comment by ndjones** [comment]
Yes, it doesn't kill the session, I hadn't suggested it did. Tidying it up should be all thats required, as it was never going to work in the current environment.

**Comment by chrisdjscott** [comment]
Slurm app has been removed in latest version of JupyterLab
